Changed naming convention of installation functions and updated install scripts.

diff --git a/check-config b/check-config
--- a/check-config
+++ b/check-config
@@ -2,7 +2,7 @@
 
 set -e
 
-link_file_or_directory ()
+symlink_config ()
 {
     # If the destination exists
     if [ -f "$1" -a -f "$2" ] || [ -d "$1" -a -d "$2" ] || [ -L "$2" ]; then
@@ -27,8 +27,8 @@ link_file_or_directory ()
                         fi
                         ;;
                     [oO])
-                        if rm "$2"; then
-                            ln -s "$1" "$2"
+                        if $3 rm "$2"; then
+                            $3 ln -s "$1" "$2"
                         else
                             printf "Failed to delete $2" 1>&2
                         fi
@@ -48,9 +48,54 @@ link_file_or_directory ()
         fi
     else
         # The destination doesn't exists, so symlink it.
-        ln -s "$1" "$2"
+        $3 ln -s "$1" "$2"
     fi
 }
+
+sudo_symlink_config () { symlink "$1" "$2" "sudo -n" }
+
+install_config ()
+{
+    if [ -e "$2" ]; then
+        if [ -f "$1" -a -f "$2" ] || [ -d "$1" -a -d "$2" ]; then
+            while !diff -ur "$1" "$2" >/dev/null 2>&1; do
+                printf "Wrong source file found for:\n$2\n"
+                printf "(D)iff changes/(O)verwrite file/(K)eep file? [Dok?] "
+                read COMMAND
+
+                if [ -z "$COMMAND" ]; then
+                    COMMAND=d
+                fi
+
+                case "$COMMAND" in
+                    [dD])
+                        printf "$2\n"; diff -u "$2" "$1" | less
+                        ;;
+                    [oO])
+                        $3 cp -r "$1" "$2" || printf "Failed to delete $2" 1>&2
+                        break
+                        ;;
+                    [kK])
+                        break
+                        ;;
+                    ?)
+                        printf "d - show diff between current and repo file\n"
+                        printf "o - overwrite current file with repo symlink\n"
+                        printf "k - keep the current file\n"
+                        printf "? - this help\n"
+                        ;;
+                esac
+            done
+
+        else
+            printf "Error installing $2, file or directory already exists."
+        fi
+    else
+        $3 cp -r "$1" "$2"
+    fi
+}
+
+sudo_install_config () { install_config "$1" "$2" "sudo -n" }
 
 install_repo ()
 {
