Switched back to password prompting sudo use, drastically simplifies code and check-config is interactive anyway.

diff --git a/check-config b/check-config
--- a/check-config
+++ b/check-config
@@ -6,9 +6,6 @@ set -e
 trap 'printf "$FILE:$FUNCNAME:$LINENO: $_\n" 1>&2' ERR
 trap 'rm -f success' EXIT
 
-# On OSX "sudo -n" returns a 0 exit code on password failure, so we use touch
-# to determine whether the command succesfully executed.
-
 # Install a symlink to a config file
 symlink_config ()
 {
@@ -40,21 +37,19 @@ symlink_config ()
                     fi
                     ;;
                 [oO])
-                    # Try to overwrite the file. See sudo note at top of file.
-                    cmd="rm -- \"$2\""
-                    cmd+=" && ln -s -- \"$1\" \"$2\""
-                    cmd+=" && sudo -u \#$UID touch success"
-
-                    # $3 contains optional sudo command
-                    $3 sh -c "$cmd"
-                    if ! rm success 2>/dev/null; then
-                        printf "Failed to resymlink $2\n" 1>&2
-                    else
+                    # Try to overwrite the file. $3 contains optional sudo
+                    # command.
+                    if $3 rm -- "$2" && $3 ln -s -- "$1" "$2"; then
                         updated=1
+                    else
+                        printf "Failed to resymlink $2\n" 1>&2
                     fi
+
+                    printf "\n"
                     break
                     ;;
                 [kK])
+                    printf "\n"
                     break
                     ;;
                 ?)
@@ -68,17 +63,12 @@ symlink_config ()
             printf "\n"
         done
     elif [ ! -e "$2" ]; then
-        # The destination doesn't exists, so try to symlink it. See sudo note
-        # at top of file.
-        cmd="ln -s -- \"$1\" \"$2\""
-        cmd+=" && sudo -u \#$UID touch success"
-
-        # $3 contains optional sudo command
-        $3 sh -c "$cmd"
-        if ! rm success 2>/dev/null; then
-            printf "Failed to symlink $2\n" 1>&2
-        else
+        # The destination doesn't exists, so try to symlink it. $3 contains
+        # optional sudo command.
+        if $3 ln -s -- "$1" "$2"; then
             updated=1
+        else
+            printf "Failed to symlink $2\n" 1>&2
         fi
     else
         printf "$2 already exists and is not a file, directory or symlink!\n" 1>&2
@@ -87,7 +77,7 @@ symlink_config ()
 
 sudo_symlink_config ()
 {
-    symlink "$1" "$2" "sudo -n"
+    symlink "$1" "$2" "sudo -p \"Enter password to symlink $2:\""
 }
 
 install_config ()
@@ -111,20 +101,18 @@ install_config ()
                     diff -ur "$2" "$1" | less
                     ;;
                 [oO])
-                    # Attempt to copy over. See sudo note at top of file.
-                    cmd="cp -r -- \"$1\" \"$2\""
-                    cmd+=" && sudo -u \#$UID touch success"
-
-                    # $3 contains optional sudo command
-                    $3 sh -c "$cmd"
-                    if ! rm success 2>/dev/null; then
-                        printf "Failed to update $2\n" 1>&2
-                    else
+                    # Attempt to copy over. $3 contains optional sudo command.
+                    if $3 cp -r -- "$1" "$2"; then
                         updated=1
+                    else
+                        printf "Failed to update $2\n" 1>&2
                     fi
+
+                    printf "\n"
                     break
                     ;;
                 [kK])
+                    printf "\n"
                     break
                     ;;
                 ?)
@@ -138,16 +126,11 @@ install_config ()
             printf "\n"
         done
     elif [ ! -e "$2" ]; then
-        # Attempt to copy over. See sudo note at top of file.
-        cmd="cp -r -- \"$1\" \"$2\""
-        cmd+=" && sudo -u \#$UID touch success"
-
-        # $3 contains optional sudo command
-        $3 sh -c "$cmd"
-        if ! rm success 2>/dev/null; then
-            printf "Failed to copy to $2\n" 1>&2
-        else
+        # Attempt to copy over. $3 contains optional sudo command.
+        if $3 cp -r -- "$1" "$2"; then
             updated=1
+        else
+            printf "Failed to copy to $2\n" 1>&2
         fi
     else
         printf "$2 already exists and is not a file or directory!\n" 1>&2
@@ -156,7 +139,7 @@ install_config ()
 
 sudo_install_config ()
 {
-    install_config "$1" "$2" "sudo -n"
+    install_config "$1" "$2" "sudo -p \"Enter password to install $2:\""
 }
 
 install_repo ()
@@ -211,7 +194,6 @@ install_repo ()
                     ;;
             esac
         done
-        printf "\n"
     fi
 
     cd - >/dev/null
