Update initial setup/configuration scripts to produce more helpful issues.

diff --git a/initial-setup b/initial-setup
--- a/initial-setup
+++ b/initial-setup
@@ -6,9 +6,20 @@ if [ "$(uname)" = "Darwin" ]; then
   . setup/osx
 fi
 
+set +o pipefail
+if ! ssh -T git@github.com 2>&1 | grep -q merijn; then
+    printf "Can't authenticate with github!\n"
+    exit 1
+fi
+set -o pipefail
+
 if ! type hg >/dev/null 2>&1; then
     printf "Mercurial not installed!\n"
     exit 1
+fi
+
+if [ ! -e ~/.hgrc ]; then
+    cp dotfiles/hgrc ~/.hgrc
 fi
 
 if ! hg config extensions.hggit >/dev/null 2>&1; then
