Add an "initial setup" script that installs relevant tools from Homebrew and sets OSX config.

diff --git a/setup/osx b/setup/osx
--- a/setup/osx
+++ b/setup/osx
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+echo "Setting default configurations."
 
 # Show bottom status bar with available space in finder
 defaults write com.apple.finder ShowStatusBar -bool true
@@ -20,3 +20,24 @@ defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
 
 # Disable smart quotes as it’s annoying for messages that contain code
 defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false
+
+hash brew 2>/dev/null || { echo >&2 "Homebrew not found. Aborting."; exit 1; }
+
+echo "Installing Homebrew tools."
+
+brew install bash
+brew install bash-completion
+brew install colordiff
+brew install wdiff
+brew install ctags
+brew install irssi
+brew install nethack
+brew install urweb
+brew install sox
+brew install the_silver_searcher
+brew install tmux --with-utf8proc
+brew install reattach-to-user-namespace
+
+brew cask install macvim
+brew cask install mactex-no-gui
+brew cask install karabiner-elements
